### ISSUE TITLE
Error arising from socket.io

### ISSUE THREAD

**Issue by jat255** [yyjhao/markmon#20]
Hello,

I cannot run markmon on Arch Linux using the latest node. After installing with `npm`, I get the following error when running markmon:

```
$ markmon                                                                                                                                                                                               express deprecated app.configure: Check app.get('env') in an if statement ../../usr/lib/node_modules/markmon/lib/Server.js:32:9
connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead ../../usr/lib/node_modules/markmon/node_modules/connect/lib/middleware/bodyParser.js:56:20
connect deprecated limit: Restrict request size at location of read ../../usr/lib/node_modules/markmon/node_modules/connect/lib/middleware/multipart.js:86:15
/usr/lib/node_modules/markmon/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/usr/lib/node_modules/markmon/node_modules/socket.io/lib/store.js:35:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/markmon/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:571:32)
```
```
node --version   ->    v7.2.1
npm --version    ->    4.0.3
```

**Comment by jat255** [comment]
Installing v6.9.2 works as expected

**Comment by tuxillator** [comment]
Is the actual issue here Node 7 support? Broke for me when I upgraded Node on Mac OS.

Edit: fixed mine by downgrading, works in Node 6.7.0:
`brew switch node 6.7.0`
